### ISSUE TITLE
curlで存在しないファイルをGETするとレスポンスが表示されない

### ISSUE THREAD

**Issue by hyoshie** [42Student-July/webserv_star_of_july#160]
ClientSocket.cppの97行目のコメントアウト外して実行しました。
ヘッダーに値が入ってなさそうです。

**Comment by hyoshie** [comment]
![キャプチャ](https://user-images.githubusercontent.com/84253679/182544305-590ace8d-9385-4f01-a436-d1f2b1687d50.PNG)
![2](https://user-images.githubusercontent.com/84253679/182544354-42cab89f-8c97-44f2-951b-bd86ed05d355.PNG)

**Comment by bayamasa** [comment]
ヘッダーの出力の仕方をredirect, error, get, cgiで変える用にserializerに機能を追加する

**Comment by bayamasa** [comment]
https://github.com/42Student-July/webserv_star_of_july/pull/200
done

**Comment by hyoshie** [comment]
ブラウザからは見れたのですが、最後のタグが不完全な状態でした。
![キャプチャ](https://user-images.githubusercontent.com/84253679/183535376-13a1ca57-e1ed-4673-a17d-140a54110790.PNG)
```sh
./webserv conf/saisho_example.conf
curl localhost:4242/not_exist
```

**Comment by bayamasa** [comment]
content-length起因なのか、bodyのbuildミスなのか検証

**Comment by bayamasa** [comment]
CRLF削除により表示されることを確認
