### ISSUE TITLE
responseのbodyの部分はcrlfではなく改行にする

### ISSUE THREAD

**Issue by yshima42** [42Student-July/webserv_star_of_july#161]
ミーティングでお話ししていた件です。

**Comment by yshima42** [comment]
修正できているか確認のテストのやり方
```
# コンパイル準備
make
# ./webserv conf/saisho_example.confをバックグラウンドで実行
make run
# dockerの起動、nginxをバックグラウンドで実行
make nginx
# テスター実行
make integration_test
# バックグラウンドのnginxとwebservのプロセスをkill
make done
```
このようにテストを動かすと、結果が添付画像のように出てくるはずです。この[ NG ]となっている部分は下にnginxとのdiffを表示してますのでこちらで確認いただければと思います。
bodyを\r\n から \nにすればbodyの[ NG ]とContent-Lengthの[ NG ]は解消されると思います。
![Screen Shot 2022-08-03 at 20 21 30](https://user-images.githubusercontent.com/87764458/182596341-32db775f-166e-4660-8597-477e752a2285.png)

**Comment by bayamasa** [comment]
done
https://github.com/42Student-July/webserv_star_of_july/pull/167
