### ISSUE TITLE
redirectが先勝ちできない

### ISSUE THREAD

**Issue by bayamasa** [42Student-July/webserv_star_of_july#164]
mapだと最初にいれた値がどれかわからない。
returnは一番最初にいれた値が優先させられるがmapのkeyは後入れでも数字が若い順に優先させられるため、どれが最初かわからなくなる
return 404
return 400

400が優先させられる。
解決策 最初以外は捨ててよい

**Comment by yshima42** [comment]
@bayamasa こちら最初以外は捨てるようにしましたが、これでばやさんの想定通りか確認ください。確認できたらクローズお願いします。

**Comment by yshima42** [comment]
統合テストで確認する
