### ISSUE TITLE
ブラウザからアクセスするとファイルがダウンロードされる

### ISSUE THREAD

**Issue by hyoshie** [42Student-July/webserv_star_of_july#191]
```
./webserv conf/saisho_example.conf
```
後にブラウザからlocalhost:4242にアクセスすると、ページが表示されずファイルがダウンロードされました。
curlで確認したらContent-Typeがapplication/octet-streamになっていました。

[commit ](https://github.com/42Student-July/webserv_star_of_july/commit/ab220668c641331d82f30872754271c8bdd1bcd7)の時点で実行したところ、すでにバグが起きていました。

**Comment by hyoshie** [comment]
![キャプチャ](https://user-images.githubusercontent.com/84253679/183276597-4f2bc370-5015-4bb7-916d-13fcd71186ac.PNG)

**Comment by hyoshie** [comment]
明日assignします

**Comment by bayamasa** [comment]
done
https://github.com/42Student-July/webserv_star_of_july/pull/195
