### ISSUE TITLE
cgiにリクエストを送るとsegv

### ISSUE THREAD

**Issue by hyoshie** [42Student-July/webserv_star_of_july#202]
```sh
./webserv conf/cgi_example.comf
cd tests/sandbox/chunked_req
./test_cgi_chunked_request.sh
```
![キャプチャ](https://user-images.githubusercontent.com/84253679/183535790-e28cd060-a651-4da9-a48f-1a0adcb47389.PNG)
![キャプチャ 2PNG](https://user-images.githubusercontent.com/84253679/183536047-7873f48d-ff41-426f-9fe6-9734f5016428.PNG)
![キャプチャ3](https://user-images.githubusercontent.com/84253679/183536049-fbef8922-f9e2-4aee-8d22-331169410930.PNG)

**Comment by yshima42** [comment]
done
